export type HallEvent = {
  id: string;
  day: number;
  title: string;
  time: string;
  category: "Class" | "Community" | "Private hire";
  room?: string;
  note?: string;
};

export const june2026Events: HallEvent[] = [
  { id: "jun-01-dance", day: 1, title: "Maillot Rose Dance School", time: "5:15pm–6:00pm", category: "Class" },
  { id: "jun-01-canine", day: 1, title: "Harrogate Canine", time: "7:00pm–10:00pm", category: "Class" },
  { id: "jun-02-drama", day: 2, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jun-02-martial", day: 2, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jun-02-craft", day: 2, title: "Craft and Chat", time: "7:30pm–9:00pm", category: "Community" },
  { id: "jun-03-pilates", day: 3, title: "Pilates", time: "7:30am–11:00am", category: "Class" },
  { id: "jun-03-tai", day: 3, title: "Tai Chi", time: "12:00pm–1:00pm", category: "Class" },
  { id: "jun-03-dance", day: 3, title: "Maillot Rose Dance School", time: "5:15pm–9:00pm", category: "Class" },
  { id: "jun-04-dance", day: 4, title: "Maillot Rose Dance School", time: "4:30pm–6:00pm", category: "Class" },
  { id: "jun-05-drama", day: 5, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jun-05-exercise", day: 5, title: "Village Exercise Team", time: "6:00pm–7:00pm", category: "Community" },
  { id: "jun-07-private", day: 7, title: "Private 70th birthday party", time: "All day", category: "Private hire" },
  { id: "jun-08-dance", day: 8, title: "Maillot Rose Dance School", time: "5:15pm–8:30pm", category: "Class" },
  { id: "jun-09-drama", day: 9, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jun-09-martial", day: 9, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jun-10-pilates", day: 10, title: "Pilates", time: "9:00am–11:00am", category: "Class" },
  { id: "jun-10-tai", day: 10, title: "Tai Chi", time: "12:00pm–1:00pm", category: "Class" },
  { id: "jun-10-dance", day: 10, title: "Maillot Rose Dance School", time: "5:15pm–9:00pm", category: "Class" },
  { id: "jun-11-dance", day: 11, title: "Maillot Rose Dance School", time: "4:30pm–6:00pm", category: "Class" },
  { id: "jun-12-drama", day: 12, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jun-12-exercise", day: 12, title: "Village Exercise Team", time: "6:00pm–7:00pm", category: "Community" },
  { id: "jun-13-dance", day: 13, title: "Maillot Rose Dance School", time: "9:00am–2:45pm", category: "Class" },
  { id: "jun-15-dance", day: 15, title: "Maillot Rose Dance School", time: "5:15pm–8:30pm", category: "Class" },
  { id: "jun-16-drama", day: 16, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jun-16-martial", day: 16, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jun-16-craft", day: 16, title: "Craft and Chat", time: "7:30pm–9:00pm", category: "Community" },
  { id: "jun-17-pilates", day: 17, title: "Pilates", time: "9:00am–11:00am", category: "Class" },
  { id: "jun-17-tai", day: 17, title: "Tai Chi", time: "12:00pm–1:00pm", category: "Class" },
  { id: "jun-17-dance", day: 17, title: "Maillot Rose Dance School", time: "5:15pm–9:00pm", category: "Class" },
  { id: "jun-18-dance", day: 18, title: "Maillot Rose Dance School", time: "4:30pm–6:00pm", category: "Class" },
  { id: "jun-19-fete", day: 19, title: "Harewood School Summer Fete", time: "All day", category: "Community" },
  { id: "jun-20-dance", day: 20, title: "Maillot Rose Dance School", time: "9:00am–2:45pm", category: "Class" },
  { id: "jun-20-leavers", day: 20, title: "Gateways School Leavers Party", time: "3:30pm–8:00pm", category: "Private hire" },
  { id: "jun-22-dance", day: 22, title: "Maillot Rose Dance School", time: "5:15pm–8:30pm", category: "Class" },
  { id: "jun-23-drama", day: 23, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jun-23-martial", day: 23, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jun-24-pilates", day: 24, title: "Pilates", time: "9:00am–11:00am", category: "Class" },
  { id: "jun-24-tai", day: 24, title: "Tai Chi", time: "12:00pm–1:00pm", category: "Class" },
  { id: "jun-24-dance", day: 24, title: "Maillot Rose Dance School", time: "5:15pm–9:00pm", category: "Class" },
  { id: "jun-25-dance", day: 25, title: "Maillot Rose Dance School", time: "4:30pm–6:00pm", category: "Class" },
  { id: "jun-26-drama", day: 26, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jun-26-exercise", day: 26, title: "Village Exercise Team", time: "6:00pm–7:00pm", category: "Community" },
  { id: "jun-27-dance", day: 27, title: "Maillot Rose Dance School", time: "9:00am–2:45pm", category: "Class" },
  { id: "jun-27-private", day: 27, title: "Private children’s party", time: "4:00pm–8:00pm", category: "Private hire" },
  { id: "jun-29-dance", day: 29, title: "Maillot Rose Dance School", time: "5:15pm–8:30pm", category: "Class", room: "Upstairs Room" },
  { id: "jun-30-drama", day: 30, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jun-30-martial", day: 30, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jun-30-craft", day: 30, title: "Craft and Chat", time: "7:30pm–9:00pm", category: "Community" },
];

export const july2026Events: HallEvent[] = [
  { id: "jul-01-dance", day: 1, title: "Maillot Rose Dance School", time: "5:15pm–9:00pm", category: "Class" },
  { id: "jul-02-dance", day: 2, title: "Maillot Rose Dance School", time: "4:30pm–6:00pm", category: "Class" },
  { id: "jul-03-drama", day: 3, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jul-03-exercise", day: 3, title: "Village Exercise Team", time: "6:00pm–7:00pm", category: "Community" },
  { id: "jul-04-dance", day: 4, title: "Maillot Rose Dance School", time: "9:00am–2:45pm", category: "Class" },
  { id: "jul-06-dance", day: 6, title: "Maillot Rose Dance School", time: "5:15pm–6:00pm", category: "Class" },
  { id: "jul-06-canine", day: 6, title: "Harrogate Canine", time: "7:00pm–10:00pm", category: "Class" },
  { id: "jul-07-martial", day: 7, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jul-07-craft", day: 7, title: "Craft and Chat", time: "7:30pm–9:00pm", category: "Community" },
  { id: "jul-08-pilates", day: 8, title: "Pilates", time: "9:00am–11:00am", category: "Class" },
  { id: "jul-08-tai", day: 8, title: "Tai Chi", time: "12:00pm–1:00pm", category: "Class" },
  { id: "jul-08-dance", day: 8, title: "Maillot Rose Dance School", time: "5:15pm–9:00pm", category: "Class" },
  { id: "jul-09-dance", day: 9, title: "Maillot Rose Dance School", time: "4:30pm–6:00pm", category: "Class" },
  { id: "jul-10-drama", day: 10, title: "Drama Den", time: "3:30pm–4:15pm", category: "Class" },
  { id: "jul-10-wine", day: 10, title: "Wine and Cheese at HVH", time: "4:30pm–11:00pm", category: "Community" },
  { id: "jul-11-dance", day: 11, title: "Maillot Rose Dance School", time: "9:00am–2:45pm", category: "Class" },
  { id: "jul-13-dance", day: 13, title: "Maillot Rose Dance School", time: "5:15pm–8:30pm", category: "Class" },
  { id: "jul-14-martial", day: 14, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jul-15-pilates", day: 15, title: "Pilates", time: "9:00am–11:00am", category: "Class" },
  { id: "jul-15-tai", day: 15, title: "Tai Chi", time: "12:00pm–1:00pm", category: "Class" },
  { id: "jul-15-dance", day: 15, title: "Maillot Rose Dance School", time: "5:15pm–9:00pm", category: "Class" },
  { id: "jul-16-dance", day: 16, title: "Maillot Rose Dance School", time: "4:30pm–6:00pm", category: "Class" },
  { id: "jul-17-leavers", day: 17, title: "Harewood Year 6 Leavers", time: "4:00pm–11:00pm", category: "Community" },
  { id: "jul-18-dance", day: 18, title: "Maillot Rose Dance School", time: "9:00am–2:45pm", category: "Class" },
  { id: "jul-21-martial", day: 21, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jul-21-craft", day: 21, title: "Craft and Chat", time: "7:30pm–9:00pm", category: "Community", note: "Last session for summer" },
  { id: "jul-22-tai", day: 22, title: "Tai Chi", time: "12:00pm–1:00pm", category: "Class" },
  { id: "jul-23-pcc", day: 23, title: "Harewood PCC Meeting", time: "7:00pm–10:00pm", category: "Community" },
  { id: "jul-24-exercise", day: 24, title: "Village Exercise Team", time: "6:00pm–7:00pm", category: "Community" },
  { id: "jul-28-martial", day: 28, title: "Martial Arts", time: "6:30pm–7:30pm", category: "Class" },
  { id: "jul-29-tai", day: 29, title: "Tai Chi", time: "12:00pm–1:00pm", category: "Class" },
  { id: "jul-31-exercise", day: 31, title: "Village Exercise Team", time: "6:00pm–7:00pm", category: "Community" },
];
